name: publish package

on:
  push:
    branches: [ "feat/auto-publish" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: clone repo
        uses: actions/checkout@v2

      - name: setup node 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"

      - name: install dependencies
        run: yarn install --frozen-lockfile

      - name: build
        run: CI=false yarn build

      - name: config npm token
        run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"

      - name: publish package
        run: npm publish